---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangpf.
--- DateTime: 1/23/19 5:30 PM
---

local stream, err = ngx.req.socket(true)
local data, partial
--stream:settimeout(3000000)
if stream then
    ngx.log(ngx.ERR, '---a client connected---')
end
--while not ngx.worker.exiting() do
    data, err, partial = stream:receive('*a')
    --repeat
        --do not receive data
        if not data then
            if err ~= 'timeout' then
                ngx.log(ngx.ERR, 'receive error:', err)
          --      return
            end
        end

        if data == nil or string.len(data)<0 then
            ngx.log(ngx.ERR, 'data is nil.')
        --    break
        end

        --received data
        ngx.log(ngx.ERR, '---successfully received data---saving to local--- ')
        local file = io.open("res.pdf","a+")
        io.output(file)
        io.write(data)
        io.close(file)

   -- until true
--end
