---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangpf.
--- DateTime: 1/23/19 4:51 PM
---
local tcpsock = ngx.socket.tcp()

--- connect;send;read timeout
tcpsock:settimeouts(6000, 6000000, 6000000)

---建立tcp连接
local host = "192.168.0.5"
local port = 1688
local ok, err = tcpsock:connect(host, port)
if not ok then
    ngx.log(ngx.ERR, "failed to connect tcp server:", err)
    return
end

local file
while not ngx.worker.exiting() do
    file = io.open("res.pdf",'a+')
    
    repeat
        --接收数据
        local line, err, partial = tcpsock:receive()

        --如果timeout，则继续接收数据
        if not line then
            if err ~= 'timeout' then
                ngx.log(ngx.ERR, 'receive error:', err)
                return
            end
        end
        --do not receive data
        if line == nil or string.len(line) < 0 then
            ngx.log(ngx.ERR, 'line is nil.')
            break
        end
        
        file:write(line)
	ngx.say(line)
	ngx.flush(true)
        ----关闭打开的文件


    until true
        file:close()
end
