---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangpf.
--- DateTime: 1/29/19 11:02 AM
---

local stream, err = ngx.req.socket(true)
--stream:settimeout(3000000)
local filename = "./test.pdf"

local file = io.open(filename, "r")
local string = file:read("*a")
local bytes, err = stream:send(string)
if err then
    ngx.log(ngx.ERR, "failed to send data to tcp server:", err)
    return
end
file:close()

--local bytes
--for line in io.lines(filename) do
--    bytes, err = stream:send(line)
--    if err then
--        ngx.log(ngx.ERR, "failed to send data to tcp server:", err)
--        return
--    end
--end
