---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangpf.
--- DateTime: 1/29/19 2:19 PM
---
function readall(s)
    local msg, err, part = s:receive("*a")
    if (not msg) and (err ~= 'timeout') then
        return nil, err
    end
    msg = msg or part
    if not msg then
        return nil, 'timeout'
    end
    return msg
end

local tcpsock = ngx.socket.tcp()

tcpsock:settimeouts(6000, 600000, 600000)

local host = "192.168.0.210"
local port = 1688
local ok, err = tcpsock:connect(host, port)
if not ok then
    ngx.log(ngx.ERR, "failed to connect tcp server:", err)
    return
end

ngx.say(readall(tcpsock))